# Generated by Django 2.1.3 on 2018-12-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('reported', models.CharField(blank=True, max_length=256)),
                ('inferred', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraProperties',
            fields=[
                ('extra_props_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitter_comments', models.TextField(blank=True)),
                ('alias', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='GeneVariantInfo',
            fields=[
                ('gene_variant_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid_for_variant', models.CharField(max_length=48)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Classification')),
                ('extra_properties', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.ExtraProperties')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='GenomicLocation',
            fields=[
                ('genomic_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly', models.CharField(blank=True, max_length=8)),
                ('chromosome', models.CharField(blank=True, max_length=8)),
                ('start', models.CharField(blank=True, max_length=24)),
                ('stop', models.CharField(blank=True, max_length=24)),
                ('accession', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='OtherMappings',
            fields=[
                ('other_mappings_id', models.AutoField(primary_key=True, serialize=False)),
                ('other_mapping', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=24)),
                ('last_eval', models.CharField(blank=True, max_length=24)),
                ('last_updated', models.CharField(blank=True, max_length=24)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('nucleotide_change', models.CharField(blank=True, max_length=24)),
                ('protein_change', models.CharField(blank=True, max_length=24)),
                ('ref_allele', models.CharField(blank=True, max_length=24)),
                ('alt_allele', models.CharField(blank=True, max_length=24)),
                ('reported_ref', models.CharField(blank=True, max_length=24)),
                ('reported_alt', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='genomic_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.GenomicLocation'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='other_mappings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.OtherMappings'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Source'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Transcript'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Variant'),
        ),
    ]
