# Generated by Django 2.1.3 on 2018-12-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('allele_id', models.AutoField(primary_key=True, serialize=False)),
                ('allele', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraProperties',
            fields=[
                ('extra_props_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitter_comments', models.TextField(blank=True)),
                ('alias', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(blank=True, max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='GeneVariantInfo',
            fields=[
                ('gene_variant_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('extra_properties', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.ExtraProperties')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='GenomicLocation',
            fields=[
                ('genomic_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('assembly', models.CharField(blank=True, max_length=8)),
                ('chromosome', models.CharField(blank=True, max_length=8)),
                ('start', models.CharField(blank=True, max_length=32)),
                ('stop', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('mapping_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MappingJoinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleotide_change', models.BooleanField()),
                ('gene_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.GeneVariantInfo')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=16)),
                ('last_eval', models.CharField(blank=True, max_length=16)),
                ('last_updated', models.CharField(blank=True, max_length=16)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript_name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptJoinTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.BooleanField()),
                ('gene_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.GeneVariantInfo')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Transcript')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_extras_id', models.AutoField(primary_key=True, serialize=False)),
                ('protein_change', models.CharField(blank=True, max_length=32)),
                ('alt_allele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alt_allele', to='variants.Allele')),
                ('ref_allele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ref_allele', to='variants.Allele')),
                ('reported_alt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_alt', to='variants.Allele')),
                ('reported_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_ref', to='variants.Allele')),
            ],
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='genomic_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.GenomicLocation'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='inferred_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inferred', to='variants.Classification'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='mappings',
            field=models.ManyToManyField(through='variants.MappingJoinTable', to='variants.Mapping'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='reported_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported', to='variants.Classification'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Source'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='transcripts',
            field=models.ManyToManyField(through='variants.TranscriptJoinTable', to='variants.Transcript'),
        ),
        migrations.AddField(
            model_name='genevariantinfo',
            name='variant_extras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variants.Variant'),
        ),
    ]
